import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/components/providers/QueryProvider";
import { SocketProvider } from "@/context/SocketContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body
          className={`${cn(`relative h-full font-sans antialiased`, `${geistSans.variable}`)}`}
        >
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1">
              <Providers>
                <SocketProvider>
                  {children}
                </SocketProvider>
              </Providers>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
